name: Run Python Script

on:
  schedule:
    - cron: '0 */2 * * *' # Run every 6 hours

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install requests
      - name: Run script
        run: |
          python src/main.py
      - name: Commit and push changes
        run: |
          git config user.name lpschat
          git config user.email lpschat@github.com
          git add .
          git commit -m "Update result"
          git push
